print ("--------------------inicio-----------------")
nome  = input ("Informe seu nome: ")
sobrenome  = input ("Informe o seu sobrnome: ")
print (nome, sobrenome )
print ("--------------------Fim-----------------")